spring.application.name=service-registry

#Port on which registry will run 
server.port=8761

#Domain/Ip address of the registry 
eureka.instance.hostname=localhost

#Do not register yourself as a microservice on the server
eureka.client.register-with-eureka=false

#Do not downloadinformatioin of all the registered microservices
eureka.client.fetch-registry=false