spring.application.name=api-gateway

server.port=8080

#To define the uri of the registry 
eureka.client.service-url.defaultZone=${eureka-endpoint}

spring.cloud.gateway.mvc.routes[0].id=movie-catelog-service
spring.cloud.gateway.mvc.routes[0].uri=${catelog-endpoint}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/movie-info/**

spring.cloud.gateway.mvc.routes[1].id=movie-streaming-service
spring.cloud.gateway.mvc.routes[1].uri=${streaming-endpoint}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/movie-stream/**
